# Generated by Django 5.0.6 on 2024-06-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analyzed_weather_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_station_name', models.CharField(default=None, max_length=15)),
                ('year', models.IntegerField()),
                ('avg_max_temp', models.FloatField(null=True)),
                ('avg_min_temp', models.FloatField(null=True)),
                ('precipitation', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='raw_weather_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_station_name', models.CharField(default=None, max_length=15, unique=True)),
                ('daily_weather_data', models.JSONField(default=None)),
            ],
        ),
    ]
