# Generated by Django 5.0.6 on 2024-06-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_weather_data',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
