# Generated by Django 5.0.6 on 2024-06-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_raw_weather_data_weather_station_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='raw_weather_data_simplified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_station_name', models.CharField(default=None, max_length=15)),
                ('daily_weather_data', models.JSONField(default=None)),
            ],
        ),
    ]
